version: '3'
services:
  mysql:
   container_name: mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: loja_virtual
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
   ports:
   - "3306:3306"
   restart: always
   networks:
      - main
  
  back:
    container_name: back
    restart: always
    build: ./back-end/loja-virtual
    working_dir: /back-end/loja-virtual
    volumes:
      - ./back-end/loja-virtual:/back-end/loja-virtual
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
    networks:
      - main

  front:
    container_name: front
    build: ./front-end/loja-virtual
    volumes:
      - ./front-end/loja-virtual:/front-end/loja-virtual/usr/src/app
    ports:
      - "4200:4200"
    depends_on:
      - mysql
      - back
    networks:
      - main

networks:
  main: